config/routes.rb
Rails.application.routes.draw do

  resources :events

  resources :users do
    get :logout, on: :collection
    post :login, on: :collection
    post :add_friend, on: :member
    delete :remove_friend, on: :member    
  end

  resources :invites

  resources :notifications, only: [:index, :destroy, :update]
  resources :friend_requests, controller: 'notifications', type: 'FriendRequest', only: [:index, :destroy, :update]
  resources :event_invites, controller: 'notifications', type: 'EventeInvite', only: [:index, :destroy, :update]
  resources :event_updates, controller: 'notifications', type: 'EventUpdates', only: [:index, :destroy, :update]
  resources :invite_rsvps, controller: 'notifications', type: 'InviteRSVPs', only: [:index, :destroy, :update]

  resources :events do
    # get ':param' => :show, on: :member
    # resources :invites
    get :chatlog, on: :member
    post :logchat, on: :member
    post :toggle_favorite, on: :member
    put :toggle_confirm, on: :member
    post :add_restaurant, on: :member
    get :foursquare, on: :member
  end

  root to: 'layouts#index'
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                  :integer          not null, primary key
#  email               :string
#  password_digest     :string
#  name                :string
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#  privacy             :boolean          default("false")
#  avatar_file_name    :string
#  avatar_content_type :string
#  avatar_file_size    :integer
#  avatar_updated_at   :datetime
#

class User < ActiveRecord::Base
	has_many :created_events, class_name: "Event", foreign_key: :creator_id
	has_many :notifications
	has_many :invites
	has_many :events, through: :invites
	has_many :favorites
	has_and_belongs_to_many :friends, 
	              class_name: "User", 
	              join_table: :friendships, 
	              foreign_key: :user_id, 
	              association_foreign_key: :friend_user_id
	has_secure_password
	validates :email, uniqueness: true
	delegate :friend_requests, :event_invites, :event_updates, to: :notifications

	has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>", :icon => "50x50>" }, :default_url => "users/default/default.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  validates_attachment_size :avatar, :less_than => 1.megabytes
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :add_friend, :remove_friend]
  before_action :clear_notifications, only: [:show]

  # GET /users
  # GET /users.json
  def index
    input = params[:search]
    if input.length > 2
      sql = "name LIKE '%#{input}%' OR email LIKE '%#{input}%'"
    else
      sql = "name LIKE '#{input.titleize}%' OR email LIKE '#{input}%'"
    end
    @users = User.where(sql)
    @users_avatars = @users.map { |user| {avatar_url: user.avatar.url(:icon), id: user.id}}
    @friends = current_user.friends
    respond_to do |format|
      format.html { render :index }
      format.json { render json: {users: @users, user_avatars: @users_avatars, friends: @friends, current_user_id: current_user.id}}
    end

  end

  # GET /users/1
  # GET /users/1.json
  def show
    @events = @user.events
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  def login
    @user = User.find_by(email: params[:email])
    if @user.authenticate(params[:password])
      session[:user_id] = @user.id
    else
      render "/"
    end
    redirect_to events_path
  end

  def logout
    reset_session
    redirect_to "/"
  end

  def add_friend
    if @user.privacy
      @user.friend_requests.create(sender_id: current_user.id)
    else
      current_user.friend_ids=current_user.friend_ids.push(@user.id)
    end
    respond_to do |format|
      format.json { render json: {name: @user.name, id: @user.id, privacy: @user.privacy}}
    end
  end

  def remove_friend
    Friendship.find_by(user_id:current_user.id, friend_user_id: @user.id)
    render :show
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        session[:user_id] = @user.id
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :avatar)
    end

    def clear_notifications
      current_user.notifications.each do |notification|
        notification.notified = true
        notification.save
      end
    end
end

app/helpers/users_helper.rb
module UsersHelper
	def current_user
		if session[:user_id]
			@current_user ||= User.find(session[:user_id])
		else
			nil
		end
	end

	def user_friend_request_path
	end
end

app/views/users/_form.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<div class="field">
  <%= form.label :email %><br>
  <%= form.text_field :email, class: "form-control"  %>
</div>
<div class="field">
  <%= form.label :name %><br>
  <%= form.text_field :name, class: "form-control"  %>
</div>
<div class="field">
  <%= form.label :password %><br>
  <%= form.text_field :password, class: "form-control"  %>
</div>
<div class="field">
  <%= form.label :password_confirmation %><br>
  <%= form.text_field :password_confirmation, class: "form-control" %>
</div>
<div class="field">
<%= form.label "Add Profile Image" %><br><br>
<%= form.file_field :avatar %>
</div>

app/views/users/_login.html.erb
      <%= form_tag login_users_path, :class => "navbar-form navbar-right" do %>
       <div class="form-group">
        <%= text_field_tag :email, params[:email], placeholder: "Email", class: "form-control" %>
      </div>
       <div class="form-group">
        <%= password_field_tag(:password, "", placeholder: "Password", class: "form-control") %>
      </div>
      <%= button_tag "Login", class: "btn btn-default" %>
      <% end %>

app/views/users/_navigation.html.erb
<nav class="navbar navbar-custom navbar-fixed-top top-nav-collapse" role="navigation">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
                    <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand page-scroll" href="#page-top">
                    <%= link_to "appetito", root_path, class: "navbar-brand" %>
                </a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
                <ul class="nav navbar-nav">
                    <!-- Hidden li included to remove active class from about link when scrolled up past about section -->
                    <li class="hidden">
                        <a href="#page-top"></a>
                    </li>
                    <% if current_user %>
                    <li><%= link_to "Events", events_path%></li>
                    <li class="dropdown" id="user_nav">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                        <%= current_user.name %>
                        <span class="caret"></span>
                        <%= image_tag current_user.avatar.url(:icon), class: "avatar avatar-mini" %>
                        <% unless current_user.notifications.where(notified: false).count == 0 %>
                            <span class="badge notification-badge"><%= current_user.notifications.where(notified: false).count %>
                            </span>
                        <% end %>
                      </a>
                      <ul class="dropdown-menu" role="menu">
                        <li><%= link_to "Profile", user_path(current_user) %></li>
                        <li><%= link_to "Logout", logout_users_path %></li>
                      </ul>
                    </li>
                    <% end %>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

app/views/users/_notification.html.erb
<div>
	<%= form_tag n, { class: "form-inline", method: :put} do %>
		<%= hidden_field_tag(:"friend_request[accept]",true) %>
    <%= button_tag(class: "btn btn-default") do %>
    Accept <span class="glyphicon glyphicon-ok" aria-hidden="true"></span> 
    <% end %>
	<% end %>
	<%= form_tag n, { class: "form-inline", method: :put}  do %>
	<%= hidden_field_tag(:"friend_request[accept]",false) %>
		<%= button_tag(class: "btn btn-default") do %>
    Reject <span class="glyphicon glyphicon-remove" aria-hidden="true"></span> 
    <% end %>
	<% end %>
</div>

app/views/users/edit.html.erb
<div class=" col-sm-offset-4 col-sm-4">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3><%= current_user == @user ? " Edit Your Profile" : "Edit User" %></h3>
    </div>
    <div class="panel-body">
      <%= form_for(@user) do |form| %>
        <%= render form %>
        <div class="actions">
           <%= form.submit "Edit", class: "btn btn-default" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/new.html.erb
<div class="col-sm-offset-4 col-sm-4">
  <div class="panel panel-default">
    <div class="panel-heading">
<h1>New User</h1>
</div>
<div class="panel-body">
<%= form_for(@user) do |form| %>
	<%= render form %>
  <br>
	<div class="actions">
	   <%= form.submit "Sign Up", class: "btn btn-default" %>
	  </div>
<% end %>

</div>
</div>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<div class="col-sm-12 hidden-xs	">
	<div class="col-xs-4 col-sm-3">
		<a href="#" class="thumbnail">
			<%= image_tag @user.avatar.url(:medium) %>
		</a>
	</div>

	<div class="col-xs-6 col-md-3">
		<p>
			<strong>Name:</strong>
			<%= @user.name %>
		</p>

		<p>
			<strong>Email:</strong>
			<%= @user.email %>
		</p>
		<% if current_user.friends && current_user.friends.include?(@user)%>
		<p>delete friend</p>
		<% elsif current_user.id != @user.id %>
		<p>add friend</p>
		<% end %>
		<% if current_user == @user %>
		<p><%= link_to 'Edit Profile', edit_user_path(current_user), { method: :get} %></p> 
		<% end %>
	</div>
</div>

<div class="col-sm-12">
	<% if current_user && current_user.id == @user.id %>
	<div class="col-md-4">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h4 class="panel-title">Notifications</h4>
			</div>
			<ul class="list-group">
				<% current_user.notifications.each do |n| %>
				<li class="list-group-item">
					<%= n.message %> <%= render 'notification', :n => n if n.type == "FriendRequest" && n.accept == nil%>
				</li>
				<% end %>
			</ul>
		</div>
	</div>
	<div class="col-md-4">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h4 class="panel-title">Events</h4>
			</div>
			<ul class="list-group">
				<% @events.each do |event| %>
				<li class="list-group-item"><%= link_to event.name, event_path(event) %></li>
				<% end %>
			</ul>
		</div>
	</div>
	<div class="col-md-4">
		<div class="panel panel-default">
			<div class="panel-heading">
				<h4 class="panel-title inline-block">Friends</h4>
				<span class="cursor glyphicon glyphicon-plus pull-right" data-toggle="modal" data-target="#friend-search-modal" aria-hidden="true"></span>
			</div>
			<ul class="media-list list-group">
				<% current_user.friends.each do |friend| %>
				<li class="media list-group-item">
					<div class="media-left">
						<%= image_tag friend.avatar.url(:thumb), class: "avatar" %>
					</div>
					<div class="media-body">
						<%= link_to friend.name, user_path(friend) %>
					</div>
				</li>
				<% end %>
			</ul>
			<% end %>
		</div>
	</div>
</div>

<div class="modal fade" id="friend-search-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title">Find New Friends</h4>
			</div>
			<div class="modal-body">
				<form class= "search" action = "/users" method= 'GET'>
					<div class="form-group">
						<input type="text" name="search" class="search-bar form-control" id="recipient-name" placeholder="Search..." data-toggle="collapse" href="#newfriend-panel" aria-expanded="false" aria-controls="newfriend-panel">
						<span class="glyphicon glyphicon-search"></span>
					</div>
				</form>
			<div id="newfriend-panel" class="collapse panel panel-default">
				<ul id="newfriend-list" class="media-list list-group">

				</ul>
			</div>
			</div>
		</div>
	</div>
</div>