config/routes.rb
Rails.application.routes.draw do

  resources :events

  resources :users do
    get :logout, on: :collection
    post :login, on: :collection
    post :add_friend, on: :member
    delete :remove_friend, on: :member    
  end

  resources :invites

  resources :notifications, only: [:index, :destroy, :update]
  resources :friend_requests, controller: 'notifications', type: 'FriendRequest', only: [:index, :destroy, :update]
  resources :event_invites, controller: 'notifications', type: 'EventeInvite', only: [:index, :destroy, :update]
  resources :event_updates, controller: 'notifications', type: 'EventUpdates', only: [:index, :destroy, :update]
  resources :invite_rsvps, controller: 'notifications', type: 'InviteRSVPs', only: [:index, :destroy, :update]

  resources :events do
    # get ':param' => :show, on: :member
    # resources :invites
    get :chatlog, on: :member
    post :logchat, on: :member
    post :toggle_favorite, on: :member
    put :toggle_confirm, on: :member
    post :add_restaurant, on: :member
    get :foursquare, on: :member
  end

  root to: 'layouts#index'
end

app/models/event.rb
# == Schema Information
#
# Table name: events
#
#  id         :integer          not null, primary key
#  creator_id :integer
#  name       :string
#  when       :datetime
#  location   :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  finalized  :boolean          default("false")
#  latitude   :float
#  longitude  :float
#  restaurant :string
#

class Event < ActiveRecord::Base
  # belongs_to :user
  belongs_to :creator, class_name: "User", foreign_key: :creator_id
  has_many :notifications, dependent: :destroy
  has_many :invites, dependent: :destroy
  has_many :chatlogs, dependent: :destroy
  has_many :restaurants, dependent: :destroy
  has_many :favorites
  has_many :users, through: :invites

  geocoded_by :location   # can also be an IP address
  after_validation :geocode

  delegate :event_invites, :event_updates, to: :notifications
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  include EventsHelper
  before_action :set_event, only: [:show, :edit, :update, :destroy, :chatlog, :toggle_confirm, :logchat, :add_restaurant]

  # GET /events
  # GET /events.json
  def index
    @events = current_user.events if current_user
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @notifications = @event.notifications
    @invitees = @event.invites
    located = @invitees.where("location IS NOT NULL") 

      # rsvp = 'Attending' OR rsvp = 'Maybe' OR rsvp = 'Undecided'"
    @chatlog = @event.chatlogs
    @hash = Gmaps4rails.build_markers(located) do |invitee, marker|
      marker.lat invitee.latitude
      marker.lng invitee.longitude
      #info window settings accept html (using info_html helper)
      marker.json({:id => invitee.user.id, :name => invitee.user.name})
    end
  end

  # GET /events/new
  def new
    if current_user
      @friends = current_user.friends
      @event = current_user.created_events.new
    else
      @event = Event.new
    end
  end

  # GET /events/1/edit
  def edit
  end

  def chatlog
    chatlog = @event.chatlogs
    #need to limit to 50
    invitees = @event.users
    invitee_avatars = invitees.map { |invitee| {avatar_url: invitee.avatar.url(:icon), id: invitee.id}}
    respond_to do |format|
      format.json { render json: {event: @event, chatlog: chatlog, current_user: current_user, invitees: invitees, invitee_avatars: invitee_avatars, avatar_url: current_user.avatar.url(:icon)}}
    end
  end

  def logchat
    @event.chatlogs.create(message: params[:message], user_id: current_user.id)
    respond_to do |format|
      format.json { render json: {message: "message received"} }
    end
  end

  def toggle_favorite
    restaurant = Restaurant.find(params[:restaurant])
    if favorited = restaurant.favorites.find_by(user_id: current_user.id)
      favorited.destroy
      puts "destroyed"
    else
      favorite = restaurant.favorites.create(user_id: current_user.id)
      puts "created"
    end
    favorite_count = restaurant.favorites.count
    respond_to do |format|
      format.json { render json: {count: favorite_count} }
    end

  end

  def toggle_confirm
    restaurant = Restaurant.find(params[:restaurant])
    params[:event] = {restaurant: restaurant.name, location: restaurant.address, finalized: true}
    @event.update(event_params)

    respond_to do |format|
      format.json { render json: @event }
    end

  end

  def add_restaurant
    restaurant = @event.restaurants.create(restaurant_params)
    restaurant.favorites.create(user_id: current_user.id)
    count = restaurant.favorites.count
    respond_to do |format|
      format.json { render json: {restaurant: restaurant, count: count} }
    end

  end

  def foursquare
    baseURL = "https://api.foursquare.com/v2/venues/explore"
    clientID = "?client_id=CSXMPXYF20VXWMX4Z0BTKHVT5VGRKA1E3ZAPKCE04ELOMX3W"
    clientSecret = "&client_secret=LQ2UIGEDAP0O5CFMQEMEYEM1KORYH4ISVPXLRSHGYNU1LMOZ"

    render text: Net::HTTP.get(baseURL + clientID + clientSecret + '&' + params[:foursquare].to_param)
  end

  # POST /events
  # POST /events.json
  def create
    invitees = params[:user_id]
    @event = current_user.created_events.new(event_params)
    respond_to do |format|
      if @event.save
        invitees.each do |id| 
          # binding.pry
          @event.event_invites.create(user_id: id, sender_id: current_user.id)
          @event.invites.create(user_id: id)
        end
        @event.invites.create(user_id: current_user.id, rsvp: "Attending")
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:user_id, :name, :when, :location, :finalized, :restaurant)
    end

    def restaurant_params
      params.require(:restaurant).permit(:name, :cuisine, :phone, :address, :rating, :price, :event_id)
    end
end

app/helpers/events_helper.rb
module EventsHelper

	def info_html(user_name)
		return "<strong style='color: blue;'>#{user_name}</strong>"
	end

	def api(coordinates)
		json = ''
		
		File.open('secret.json', 'r') do |f|
		  f.each_line do |line|
		    json << line
		  end
		end

		consumer_key = json_hash['key']
		consumer_secret = json_hash['con_secret']
		token = json_hash['token']
		token_secret = json_hash['token_secret']

		Yelp.client.configure do |config|
		  config.consumer_key = consumer_key
		  config.consumer_secret = consumer_secret
		  config.token = token
		  config.token_secret = token_secret
		end

		params = { term: "food", limit: 5, }


	end
end

app/views/events/_chat.html.erb
<div id="chatroom"  id="chat_window_1">
        <div class="panel panel-default">
            <div class="panel-heading top-bar">
                <div class="col-md-8 col-xs-8">
                    <h3 class="panel-title"><span class="glyphicon glyphicon-comment"></span> <%=@event.name%> - <%= current_user.name %></h3>
                </div>
                <div class="col-md-4 col-xs-4" style="text-align: right;">
                    <a href="#"><span id="minim_chat_window" class="glyphicon glyphicon-minus icon_minim"></span></a>
                </div>
            </div>

            <div id="chatwindow" class="panel-body msg_container_base">


            </div>


            <div class="panel-footer">
                <div id="userinput" class="input-group">
                    <input id="textbox" type="text" class="form-control input-sm chat_input" placeholder="Write your message here..." />
                    <span class="input-group-btn">
                        <button class="btn btn-sm" id="submitchat">Send</button>
                    </span>
                </div>
            </div>
        </div>
</div>

    
<!-- <div class="btn-group dropup">
    <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
        <span class="glyphicon glyphicon-cog"></span>
        <span class="sr-only">Toggle Dropdown</span>
    </button>
    <ul class="dropdown-menu" role="menu">
        <li><a href="#" id="new_chat"><span class="glyphicon glyphicon-plus"></span> Novo</a></li>
        <li><a href="#"><span class="glyphicon glyphicon-list"></span> Ver outras</a></li>
        <li><a href="#"><span class="glyphicon glyphicon-remove"></span> Fechar Tudo</a></li>
        <li class="divider"></li>
        <li><a href="#"><span class="glyphicon glyphicon-eye-close"></span> Invisivel</a></li>
    </ul>
</div> -->

app/views/events/_favorite.html.erb
<div class="favorite-panel col-xs-3">
	<div id= "<%= restaurant.id %>"class="panel panel-default">
		<div class="panel-heading">
		  <h4 id="name"><%= restaurant.name %></h4>
		</div>
		<div class="panel-body">
			<h5><%= restaurant.cuisine %></h5>
			<h5><%= '$' * restaurant.price %></h5>
			<h5><%= restaurant.rating %></h5>
			<% if current_user.id == @event.creator.id %>
				<% if restaurant.address == @event.location %>
			  	<span aria-hidden="true" class="glyphicon glyphicon-ok confirmed cursor"></span>
			  <% else %>
			  	<span aria-hidden="true" class="glyphicon glyphicon-ok confirm cursor"></span>
			  <% end %>
			<% end %>
		  <% if restaurant.favorites.find_by(user_id: current_user.id) == nil%> 
		   <span aria-hidden="true" class="glyphicon glyphicon-heart favorite cursor"><%= restaurant.favorites.count %></span>
		  <% else %>
		  	<span aria-hidden="true" class="glyphicon glyphicon-heart favorited cursor"><%= restaurant.favorites.count %></span>
		  <% end %> 
		</div>
	</div>
</div>

app/views/events/_form.html.erb
<% if @event.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

  <ul>
    <% @event.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="field">
  <%= form.label :name %><br>
  <%= form.text_field :name, class: "form-control"%>
</div>


<div class="field">
    <div class="form-group">
      <%= form.label :when %><br>
      <div class='input-group date' id='datetimepicker1' data-date-format="DD/MM/YYYY hh:mm A">
        <%= form.text_field :when, class: "form-control" %>
        <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span>
      </span>
    </div>
    <script type="text/javascript">
    $(function () {
      $('#datetimepicker1').datetimepicker();
    });
    </script>
  </div>
</div>

app/views/events/_login.html.erb
<%= form_tag login_users_path, {:class => "navbar-form navbar-right", :id => "login-form"} do %>
 <div class="form-group">
  <%= text_field_tag :email, params[:email], placeholder: "Email", class: "form-control" %>
</div>
 <div class="form-group">
  <%= password_field_tag(:password, "", placeholder: "Password", class: "form-control") %>
</div>
<%= button_tag "Login", class: "btn btn-default btn-dark" %>
<% end %>

app/views/events/_map.html.erb
<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>

<div class="panel-heading top-bar">
	<%= form_tag current_user.invites.find_by(event_id: @event.id), {method: :put, id: "add-location"} do %>
		<div class="input-group">
		<%= text_field_tag(:'invite[location]',value =nil, options={placeholder: "Insert location here.", class: "form-control input-sm"}) %>
		<span class="input-group-btn"> 
		<%= button_tag "Set Location", class: "btn btn-default btn-sm" %>
	</span>
	</div>
	<% end %>
</div>

<div class="panel-body">
<div id="map" class="col-xs-6" style='min-height: 400px;'></div>

<script type="text/javascript">
	handler = Gmaps.build('Google');
	map = handler.buildMap({
	    provider: {
	      disableDefaultUI: true,
	      zoomControl: true,
        zoomControlOptions: {
            style: google.maps.ZoomControlStyle.SMALL,
            position: google.maps.ControlPosition.LEFT_TOP
        },
	      // draggable: false,
	      scrollwheel: false,
	      panControl: false
	      // pass in other Google Maps API options here
	    },
	    internal: {
	      id: 'map'
	    }
	  },
	  function(){
	  	json = <%=raw @hash.to_json %>
    	map = handler.map.serviceObject
    	center = map.center
	    markers = [];
	    searchMarkers = [];
	    bounds = new google.maps.LatLngBounds();
	    console.log(bounds, "these are the bounds")
	    maxlat = maxlng = minlat = minlng = undefined
	    json.forEach(function (obj) {
	    	
	    	buildMarker(obj);
	    	setRadius(obj.lat, obj.lng);
	    });
	    // debugger
	    
	    map.fitBounds(calibrate(bounds));
	    window.radius = measure (maxlat, maxlng, minlat, minlng)/1.5
	    window.center = map.getCenter();
	    console.log(radius)

	    //put ajax call here and access yelp API in ruby to hide secret
	  }
	);
	function measure(lat1, lon1, lat2, lon2){  // generally used geo measurement function
	    var R = 6378.137; // Radius of earth in KM
	    var dLat = (lat2 - lat1) * Math.PI / 180;
	    var dLon = (lon2 - lon1) * Math.PI / 180;
	    var a = Math.sin(dLat/2) * Math.sin(dLat/2) +
	    Math.cos(lat1 * Math.PI / 180) * Math.cos(lat2 * Math.PI / 180) *
	    Math.sin(dLon/2) * Math.sin(dLon/2);
	    var c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1-a));
	    var d = R * c;
	    return d * 1000; // meters
	}

	function calibrate(bounds) {
		var calibration =0.0007
		bounds.Ba.k -= calibration
		bounds.Ba.j += calibration
		bounds.ua.j -= calibration
		bounds.ua.k += calibration
		return bounds
	}



	function buildMarker(obj) {
		var myLatlng = new google.maps.LatLng(obj.lat, obj.lng)
		var contentString = obj.name
		var infowindow = new google.maps.InfoWindow({
			content: contentString
		})
		var marker =  new google.maps.Marker({
			position: myLatlng,
			map: handler.map.serviceObject,
			title: ""+obj.id
		})
		google.maps.event.addListener(marker, 'mouseover',function () {
			infowindow.open(map, marker);
		})

		google.maps.event.addListener(marker, 'mouseout', function () {
			infowindow.close();
		})
		bounds.extend(myLatlng)
		markers.push(marker)
	}

	function setRadius(lat,lng) {
		maxlat = Math.max(maxlat, lat) || lat
		minlat = Math.min(minlat, lat) || lat
		maxlng = Math.max(maxlng, lng) || lng
		minlng = Math.min(minlng, lng) || lng
	}

	function objectToMarker(object) {
		this.lat = object.latitude
		this.lng = object.longitude
		this.id = object.user_id
		this.name
	}
	
</script>

app/views/events/_navigation.html.erb
<nav class="navbar navbar-custom navbar-fixed-top top-nav-collapse" role="navigation">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
                    <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand page-scroll" href="#page-top">
                    <%= link_to "appetito", root_path, class: "navbar-brand" %>
                </a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
                <ul class="nav navbar-nav">
                    <!-- Hidden li included to remove active class from about link when scrolled up past about section -->
                    <li class="hidden">
                        <a href="#page-top"></a>
                    </li>
                    <% if current_user %>
                    <li><%= link_to "Events", events_path%></li>
                    <li class="dropdown" id="user_nav">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                        <%= current_user.name %>
                        <span class="caret"></span>
                        <%= image_tag current_user.avatar.url(:icon), class: "avatar avatar-mini" %>
                        <% unless current_user.notifications.where(notified: false).count == 0 %>
                            <span class="badge notification-badge"><%= current_user.notifications.where(notified: false).count %>
                            </span>
                        <% end %>
                      </a>
                      <ul class="dropdown-menu" role="menu">
                        <li><%= link_to "Profile", user_path(current_user) %></li>
                        <li><%= link_to "Logout", logout_users_path %></li>
                      </ul>
                    </li>
                    <% end %>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

app/views/events/_rsvp.html.erb
<li class="media list-group-item">
<div id="<%= invite.user.id %>" class="col-xs-12">
  <div class="col-xs-6 col-md-4">
    <%= image_tag invite.user.avatar.url(:icon), class: "avatar" %>
    <%= invite.user.name %>
  </div>
  <div id="rsvp-button-container" class="col-xs-6 col-md-4">
  	<% if invite.rsvp == "Attending" %>
  		<% arsvp = "btn-inverse" %>
  	<% elsif invite.rsvp == "Maybe" %>
  		<% mrsvp = "btn-inverse" %>
  	<% elsif invite.rsvp == "Not Attending" %>
  		<% nrsvp = "btn-inverse" %>
  	<% else %>
  		<% arsvp = mrsvp = nrsvp = nil %>
  	<% end %>
	    <% if invite.user == current_user %>
	    <button class="btn btn-default rsvps <%= arsvp %>"><span class="glyphicon glyphicon-ok" aria-hidden="true"></button>
	    <button class="btn btn-default rsvps <%= mrsvp %>"><strong>?</strong></button>
	    <button class="btn btn-default rsvps <%= nrsvp %>"><span class="glyphicon glyphicon-remove" aria-hidden="true"></button>
	    <% else %>
	    <button class="btn btn-default <%= arsvp ? arsvp : "btn-light" %>"><span class="glyphicon glyphicon-ok" aria-hidden="true"></button>
	    <button class="btn btn-default <%= mrsvp ? mrsvp : "btn-light" %>"><strong>?</strong></button>
	    <button class="btn btn-default <%= nrsvp ? nrsvp : "btn-light" %>"><span class="glyphicon glyphicon-remove" aria-hidden="true"></button>
	    <% end %>
   </div>
</div>
</li>

app/views/events/edit.html.erb
<div class="col-sm-offset-4 col-sm-4">
  <div class="panel panel-default">
    <div class="panel-heading">
<h3>Editing Event</h3>
</div>
<div class="panel-body">

<%= form_for(@event) do |form| %>
	<h4>Host: <%= @event.creator.name %></h4>
	<%= render form %>
  <div class="actions">
    <%= form.submit class: "btn btn-default" %>
  </div>
<% end %>
</div>
</div>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<div class="col-xs-12 col-sm-offset-1 col-sm-10">
<div class="panel panel-default">
      <div class="panel-heading">
  <%= link_to new_event_path do %>
    <h3><span class="glyphicon glyphicon-plus cursor" aria-hidden="true"></span>
      Add Event</h3>
    <% end %>
    </div>
    <% if @events %>
  <ul class="media-list list-group">
    <% @events.each do |event| %>
      <li class="media list-group-item">
        <div class="media-left col-xs-2">
          <span class="glyphicon glyphicon-calendar large" aria-hidden="true"></span>
        </div>
          <div class="media-body col-xs-5">
            <%= link_to event do %>
            <h4 class="inline-block"><%= event.name %></h4>
            <% end %>
             <% if current_user.id == event.creator.id %>
              <%= link_to edit_event_path(event) do %>
                <button class="btn btn-default btn-circle-sm"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></button>
              <% end %>
              <%= link_to event, method: :delete do %>
                <button class="btn btn-default btn-circle-sm"><span class="glyphicon glyphicon-remove" aria-hidden="true"></button>
              <% end %>
            <% end %>
            <p><%= event.when.to_formatted_s(:long_ordinal) %></p>
            <%= event.location %>
          </div>
           <div class="media-body col-xs-5">
              <ul>
            <% event.invites.each do |invite| %>
             <%= image_tag invite.user.avatar.url(:icon), class: "avatar avatar-mini" %>
            <% end %>
            </ul>
           </div>
          <% end %>
        </li>
    <% end %>
    </ul>
        </div>
      </div>

app/views/events/new.html.erb
<div class='col-sm-offset-4 col-sm-4'>
    <div class="panel panel-default">
    <div class="panel-heading">
<h3>New Event</h3>
</div>
<div class="panel-body">
<%= form_for(@event) do |form| %>
	<strong>Host: <%= @event.creator.name %></strong>
	<%= render form %>
	<strong>Invite</strong><br>
	<% @friends.each do |friend| %>
		<%= check_box_tag "user_id[]", friend.id %>
		<%= friend.name %><br>
	<% end %>
  <div class="actions">
    <%= form.submit class: "btn btn-default" %>
  </div>
<% end %>
</div>
</div>
</div>

app/views/events/show.html.erb
<div class="col-xs-12 col-sm-offset-1 col-sm-10">
  <div id="subnav" class="panel panel-default">
    <div class="panel-heading">
      <%= link_to events_path do %>
        
          <h3 class="inline-block">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            <%= @event.name %>
          </h3>
          <% if current_user.id == @event.creator.id %>
            <%= link_to edit_event_path(@event) do %>
              <button class="btn btn-default btn-circle-sm"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></button>
            <% end %>
            <%= link_to @event, method: :delete do %>
              <button class="btn btn-default btn-circle-sm"><span class="glyphicon glyphicon-remove" aria-hidden="true"></button>
            <% end %>
          <% end %>
        

          <% if @event.when %>
            <h3 class="pull-right"><%= @event.when.to_formatted_s(:long_ordinal) %><h3>
          <% end %>

      <%end%>
    </div>
     

    <div class="panel-body text-center">
      <div id="event-subnav">

        <div class="subnav-button col-xs-3 accent-border-top" data-target="#rsvp-container">
          <div id="rsvp-button">
            <%= image_tag "display/icons/friends.svg", class: "subnav-icon" %>
          </div>
        </div>

        <div class="subnav-button col-xs-3 accent-border-top" data-target="#chat-container">
          <div id="chat-button">
            <%= image_tag "display/icons/chat.svg", class: "subnav-icon" %>
          </div>
        </div>

        <div class="subnav-button col-xs-3 accent-border-top" data-target="#map-container">
          <div id="map-button">
            <%= image_tag "display/icons/location.svg", class: "subnav-icon" %>
          </div>
        </div>

        <div class="subnav-button col-xs-3 accent-border-top" data-target="#favorite-container">
          <div id="favorite-button">
            <%= image_tag "display/icons/utensils.svg", class: "subnav-icon" %>
          </div>
        </div>

      </div>
    </div>
  </div>
</div>


<div class="col-xs-12 col-sm-offset-1 col-sm-10">

  <div id="toggle-container">

    <div id="rsvp-container">
      <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title inline-block">Invited</h3>
           <button id="invite-friends-button" class="btn btn-default btn-sm pull-right" data-toggle="modal" data-target="#friend-invite-modal">Invite Friends</button>
        </div>
        <ul class="media-list list-group">
          <% @invitees.each do |invite| %>
          <%= render "rsvp", :invite => invite %>
          <% end %>
          </ul>
      </div>
    </div>

    <div id="chat-container" class="hidden">
      <%= render "chat" %>
    </div>
    
    <div id="map-container" class="hidden">

      <div>
        <div class="panel panel-default">
        <%= render "map" %>
        <div class="col-xs-6">
          <%= form_tag foursquare_event_path, id: "search" do %>
          <%= select_tag "select-cuisine", options_for_select([['Thai','Thai'], ['Mexican','Mexican'],['Italian','Italian'], ['American','American'],['Korean','Korean'], ['Japanese','Japanese'],['French','French'],['Diner','Diner'],['Steakhouse','Steakhouse'],['Mediterranean','Mediterranean'],['Cuban', 'Cuban'], ['Seafood', 'Seafood'],['Barbecue', 'Barbecue'], ['Vegan','Vegan'], ['Vegetarian', 'Vegetarian']], class: "form-control") %>
          <div class="btn-group" data-toggle="buttons">
          <label class="btn btn-default btn-sm">
          <%= radio_button_tag(:price, "1") %>
          $
          </label>
          <label class="btn btn-default btn-sm">
          <%= radio_button_tag(:price, "2") %>
          $$
          </label>
          <label class="btn btn-default btn-sm">
          <%= radio_button_tag(:price, "3") %>
          $$$
          </label>
          </div>
          <div class="btn-group" data-toggle="buttons">
          <label class="btn btn-default btn-sm">
          <%= check_box_tag(:reservation, "true") %>Reservations
          </label>
          </div>
          <button type='submit' class="fs btn btn-default btn-sm btn-accent">Find Restaurants</button>
          <% end %>
        </div>
        <div id='results' class="col-xs-6"></div>
      </div>  
    </div>
    </div>
  </div>

    <div id="favorite-container" class="hidden">
      <div id="favorite-wrapper">
        <% @event.restaurants.each do |restaurant| %>
        <%= render "favorite", {:restaurant => restaurant} %>
        <% end %>
      </div>
    </div>
  </div>

  <div class="modal fade" id="friend-invite-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          <h4 class="modal-title" id="exampleModalLabel">Select Friends to Invite</h4>
        </div>
        <div class="modal-body">
          <ul class="media-list list-group">
            <% current_user.friends.reject { |invited| @event.users.include?(invited) }.each do |friend| %>
            <li class="media list-group-item">
              <div class="media-left">
                <%= image_tag friend.avatar.url(:thumb), class: "avatar" %>
              </div>
              <div class="media-body">
                <%= friend.name %>
              </div>
            </li>
            <% end %>
          </ul> 
        </div>
      </div>
    </div>
  </div>
    