config/routes.rb
Rails.application.routes.draw do

  resources :events

  resources :users do
    get :logout, on: :collection
    post :login, on: :collection
    post :add_friend, on: :member
    delete :remove_friend, on: :member    
  end

  resources :invites

  resources :notifications, only: [:index, :destroy, :update]
  resources :friend_requests, controller: 'notifications', type: 'FriendRequest', only: [:index, :destroy, :update]
  resources :event_invites, controller: 'notifications', type: 'EventeInvite', only: [:index, :destroy, :update]
  resources :event_updates, controller: 'notifications', type: 'EventUpdates', only: [:index, :destroy, :update]
  resources :invite_rsvps, controller: 'notifications', type: 'InviteRSVPs', only: [:index, :destroy, :update]

  resources :events do
    # get ':param' => :show, on: :member
    # resources :invites
    get :chatlog, on: :member
    post :logchat, on: :member
    post :toggle_favorite, on: :member
    put :toggle_confirm, on: :member
    post :add_restaurant, on: :member
    get :foursquare, on: :member
  end

  root to: 'layouts#index'
end

app/controllers/layouts_controller.rb
class LayoutsController < ApplicationController
  
end

app/views/layouts/_navigation.html.erb
<nav id="landing-nav" class="navbar navbar-custom navbar-fixed-top" role="navigation">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-main-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand page-scroll" href="#page-top">
                    appetito
                </a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
                <ul class="nav navbar-nav">
                    <!-- Hidden li included to remove active class from about link when scrolled up past about section -->
                    <li class="hidden">
                        <a href="#page-top"></a>
                    </li>
                    <% if !current_user %>
                    <li>
                        <a class="page-scroll" href="#about">About</a>
                    </li>
                    <li>
                        <a class="page-scroll" href="#signup">Sign Up</a>
                    </li>
                    <% end %>
                    <% if current_user %>
                    <li><%= link_to "Events", events_path%></li>
                    <li class="dropdown" id="user_nav">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                        <%= current_user.name %>
                        <span class="caret"></span>
                        <%= image_tag current_user.avatar.url(:icon), class: "avatar avatar-mini" %>
                        <% unless current_user.notifications.where(notified: false).count == 0 %>
                            <span class="badge notification-badge"><%= current_user.notifications.where(notified: false).count %>
                            </span>
                        <% end %>
                      </a>
                      <ul class="dropdown-menu" role="menu">
                        <li><%= link_to "Profile", user_path(current_user) %></li>
                        <li><%= link_to "Logout", logout_users_path %></li>
                      </ul>
                    </li>
                    <% else %>
                      <%= render 'events/login' %>
                    <% end %>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>appetito</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body id="page-top" data-spy="scroll" data-target=".navbar-fixed-top">
<%= render :partial => "navigation" %>
<%= yield %>

</body>
</html>

app/views/layouts/index.html.erb
    <!-- Intro Header -->
    <header class="intro">
        <div class="intro-body">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-md-8 col-md-offset-2">
                        <h1 class="brand-heading">appetito</h1>
                        <p class="intro-text">Find the right place to dine.</p>
                        <a class="page-scroll" href="#signup" ><h3>Guest Login</h3></a>
                        <a href="#about" class="btn btn-lg page-scroll pulse">
                            <span class="glyphicon glyphicon-chevron-down" aria-hidden="true"></span> 
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <!-- Invite Section -->
    <div class="paper accent-frame">
    <section id="about" class="container content-section">
        <div class="row">
            <div class="col-lg-4 text-center">
                <%= image_tag "display/icons/chat.svg", class: "intro-icon" %><h2 class="inline-block">Invite Friends</h2>
                <p>Create a plan to dine out and invite your friends to a group chat.</p>
            </div>
            <div class="col-lg-4 text-center">
                <%= image_tag "display/icons/utensils.svg", class: "intro-icon" %><h2 class="inline-block">Find Restaurants</h2>
                <p>Appetito locates restaurants based on you and your friends' locations. Narrow down choices with price, cuisine, and reservation filters.</p>
            </div>
            <div class="col-lg-4 text-center">
                <%= image_tag "display/icons/check.svg", class: "intro-icon" %><h2 class="inline-block">Vote and Confirm</h2>
                <p>Vote on your favorites as a group and confirm the restaurant to dine together.</p>
            </div>
        </div>
    </section>
</div>

<!-- Splash Graphic -->
<div id="bg2-intro">
</div>

    <!-- Sign Up-->
    <div class="dark accent-frame">
    <section id="signup" class="container content-section">
        <div class="row">
            <div class="col-lg-offset-4 col-lg-4">
                <%= button_to "Sign Up", new_user_path, {:class => "btn btn-default btn-lg btn-block btn-accent margin-10", :method => :get}  %>

                <%= form_tag login_users_path do %>
                 <div class="form-group">
                  <%= hidden_field_tag :email, params[:email], value: "guest@email.com" %>
                </div>
                 <div class="form-group">
                  <%= hidden_field_tag(:password, "", value: "password") %>
                </div>
                <%= button_tag "Guest Log In", class: "btn btn-default btn-lg btn-block btn-accent margin-10" %>
                <% end %>

               



            </div>
        </div>
    </section>
</div>

<!-- Splash Graphic -->
<div id="bg3-intro">
</div>


    <!-- Creators -->
    <div class="accent-frame">
    <section id="creators" class="container content-section">
        <div class="row text-center">
            <div class="col-lg-offset-1 col-lg-5">
                <h3 class="margin-10 inline-block">Eunice Kim</h3>
                <strong>Project Manager</strong>
            </div>
            <div class="col-lg-5">
                <h3 class="margin-10 inline-block">Ciara Foran</h3>
                <strong>Web Developer</strong>
            </div>
        </div> 
        <div class="row text-center">
            <div class="col-lg-offset-1 col-lg-5">
                <h3 class="margin-10 inline-block">Remina Greenfield</h3>
                <strong>Web Developer</strong>
            </div>
            <div class="col-lg-5">
                <h3 class="margin-10 inline-block">George Lu</h3>
                <strong>Web Developer</strong>
            </div>
        </div>
    </section>
</div>
    

    <!-- Footer -->
    <footer>
        <div class="container text-center">
            <p>Copyright &copy; PrettYetti 2015</p>
        </div>
    </footer>